name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Get Architecture cache
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev ccache libgdbm-dev libgdbm-compat-dev git zip unzip

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0" virtualenv buildozer

      - name: Build Android APK
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Coupe-du-Monde-2026-APK
          path: bin/*.apk
