name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev ccache libgdbm-dev libgdbm-compat-dev git zip unzip

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0" virtualenv buildozer

      - name: Build with Buildozer
        run: |
          # On efface les variables globales de GitHub pour forcer une installation locale propre
          unset ANDROID_HOME
          unset ANDROID_NDK_HOME
          export ANDROID_SDK_ROOT=""
          
          # On lance le build
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Coupe-du-Monde-2026-APK
          path: bin/*.apk
